Repository fineanmol/Annoying-submit-button, pull requests merged in 2022-10, with the labels that each got.

#5 Project preview added and contributors image service added to README
  README.md
  content/preview.gif
Labels: hacktoberfest-accepted

#12 Added cursor pointer
  src/App.css
Labels: hacktoberfest-accepted

#14 Improve CSS design of the web-page #9
  package-lock.json
  src/App.css
  src/App.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
Labels: hacktoberfest-accepted

#25 Contribution2
  README.md
Labels: hacktoberfest-accepted

#26 Update README.md
  README.md
Labels: hacktoberfest-accepted

#44 text align property fixed for mobile design
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
Labels: hacktoberfest-accepted

#41 Added smooth transition to submit button
  src/App.js
  yarn.lock
Labels: hacktoberfest-accepted

#37 border added with dynamic color
  src/App.css
  src/App.js
  src/components/ThemeButton/ThemeButton.jsx
Labels: hacktoberfest-accepted

#36 Footer styling is done to make it more attractive
  src/App.css
Labels: hacktoberfest-accepted

#39 Improved UI
  package-lock.json
  src/App.css
  src/components/Button/Button.jsx
  src/components/Footer/Footer.css
Labels: conflicted PR

#33 Create interval_scheduling.cpp
  interval_scheduling.cpp
Labels: good first issue, hacktoberfest-accepted

#90 Fix Password Validation
  src/App.js
Labels: conflicted PR

#113 Implement eslint for lint code
  .eslintignore
  .eslintrc.js
  package.json
  src/App.js
  src/components/Button/Button.jsx
  src/components/Button/index.jsx
  src/components/Footer/Footer.jsx
  src/components/Footer/index.jsx
  src/components/ThemeButton/ThemeButton.jsx
  src/components/ThemeButton/index.jsx
  src/custom-hooks/useMediaQuery.js
  src/index.js
Labels: conflicted PR

#140 Disabled Scroll
  src/App.css
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
Labels: hacktoberfest-accepted

#147 fixed footer section for xl and 2xl screen
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
Labels: conflicted PR
